const ADMIN_TRANSACTION = 1950
const EDIT_TRANSACTION = 1951
const VIEW_TRANSACTION = 1952

let DeviceTransactions = {
    CREATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    FIND_ALL: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    FIND_BY_ID: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    UPDATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    UNLOCK:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    CHANGE_STATUS:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    REMOVE:ADMIN_TRANSACTION
}

export default DeviceTransactions