const ADMIN_TRANSACTION = 1850
const EDIT_TRANSACTION = 1851
const VIEW_TRANSACTION = 1852

let NoScheduledStopTransactions = {
    CREATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    FIND_ALL: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    FIND_BY_ID: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    UPDATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    UNLOCK:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    CHANGE_STATUS:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    REMOVE:ADMIN_TRANSACTION
}

export default NoScheduledStopTransactions