const ADMIN_TRANSACTION = 550
const EDIT_TRANSACTION = 551
const VIEW_TRANSACTION = 552

let ProductTransactions = {
    CREATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    FIND_ALL: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    FIND_BY_ID: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    UPDATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    UNLOCK:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    CHANGE_STATUS:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    REMOVE:ADMIN_TRANSACTION
}

export default ProductTransactions