const ADMIN_TRANSACTION = 1750
const EDIT_TRANSACTION = 1751
const VIEW_TRANSACTION = 1752

let ScheduledStopTransactions = {
    CREATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    FIND_ALL: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    FIND_BY_ID: [ADMIN_TRANSACTION,VIEW_TRANSACTION,EDIT_TRANSACTION],
    UPDATE: [ADMIN_TRANSACTION,EDIT_TRANSACTION],
    UNLOCK:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    CHANGE_STATUS:[ADMIN_TRANSACTION,EDIT_TRANSACTION],
    REMOVE:ADMIN_TRANSACTION
}

export default ScheduledStopTransactions